buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.4.1'
        classpath 'androidx.navigation:navigation-safe-args-gradle-plugin:2.7.7'
    }
}


tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}
